/**
 * Configuration des packs d'assets
 * Si vous renommez un dossier dans /public/packages/, mettez à jour le chemin correspondant ici
 * Le nom de la catégorie dans l'app sera automatiquement extrait du nom du dossier
 */

export interface AssetPackConfig {
	basePath: string;
	files: string[];
	type: "floor" | "wall" | "block" | "water" | "character" | "enemy" | "nature" | "furniture" | "decoration" | "resource";
	catName: string; // Nom de la catégorie - les packs avec le même catName seront groupés dans le même accordéon
}

export const ASSET_PACKS: Record<string, AssetPackConfig> = {
	// Forest Pack - Si vous renommez le dossier, changez juste le chemin ici
	forest: {
		catName: "Nature",
		basePath: "/packages/KayKit_Forest_Nature_Pack_1.0_FREE/Assets/gltf",
		files: [
			"Tree_1_A_Color1.gltf", "Tree_1_B_Color1.gltf", "Tree_1_C_Color1.gltf",
			"Tree_2_A_Color1.gltf", "Tree_2_B_Color1.gltf", "Tree_2_C_Color1.gltf",
			"Tree_2_D_Color1.gltf", "Tree_2_E_Color1.gltf",
			"Tree_3_A_Color1.gltf", "Tree_3_B_Color1.gltf", "Tree_3_C_Color1.gltf",
			"Tree_4_A_Color1.gltf", "Tree_4_B_Color1.gltf", "Tree_4_C_Color1.gltf",
			"Tree_Bare_1_A_Color1.gltf", "Tree_Bare_1_B_Color1.gltf", "Tree_Bare_1_C_Color1.gltf",
			"Tree_Bare_2_A_Color1.gltf", "Tree_Bare_2_B_Color1.gltf", "Tree_Bare_2_C_Color1.gltf",
			"Rock_2_A_Color1.gltf", "Rock_2_B_Color1.gltf", "Rock_2_C_Color1.gltf",
			"Rock_2_D_Color1.gltf", "Rock_2_E_Color1.gltf", "Rock_2_F_Color1.gltf",
			"Rock_2_G_Color1.gltf", "Rock_2_H_Color1.gltf",
			"Rock_3_A_Color1.gltf", "Rock_3_B_Color1.gltf", "Rock_3_C_Color1.gltf",
			"Rock_3_D_Color1.gltf", "Rock_3_E_Color1.gltf", "Rock_3_F_Color1.gltf",
			"Rock_3_G_Color1.gltf", "Rock_3_H_Color1.gltf", "Rock_3_I_Color1.gltf",
			"Rock_3_J_Color1.gltf", "Rock_3_K_Color1.gltf", "Rock_3_L_Color1.gltf",
			"Rock_3_M_Color1.gltf", "Rock_3_N_Color1.gltf", "Rock_3_O_Color1.gltf",
			"Rock_3_P_Color1.gltf", "Rock_3_Q_Color1.gltf", "Rock_3_R_Color1.gltf",
		],
		type: "nature",
	},

	// Dungeon Pack - Floor Tiles (separated to have correct type)
	dungeonFloor: {
		catName: "Donjon",
		basePath: "/packages/KayKit_DungeonRemastered_1.1_FREE/Assets/gltf",
		files: [
			"floor_tile_small.gltf", 
			"floor_tile_small_decorated.gltf", 
			"floor_tile_small_corner.gltf",
			"floor_tile_small_broken_A.gltf",
			"floor_tile_small_broken_B.gltf",
			"floor_tile_small_weeds_A.gltf",
			"floor_tile_small_weeds_B.gltf",
			"floor_tile_large.gltf",
			"floor_tile_large_rocks.gltf",
			"floor_tile_grate.gltf",
			"floor_tile_grate_open.gltf",
			"floor_tile_big_grate.gltf",
			"floor_tile_big_grate_open.gltf",
			"floor_tile_big_spikes.gltf",
			"floor_tile_extralarge_grates.gltf",
			"floor_tile_extralarge_grates_open.gltf",
			"floor_wood_small.gltf",
			"floor_wood_small_dark.gltf",
			"floor_wood_large.gltf",
			"floor_wood_large_dark.gltf",
			"floor_dirt_small_A.gltf",
			"floor_dirt_small_B.gltf",
			"floor_dirt_small_C.gltf",
			"floor_dirt_small_D.gltf",
			"floor_dirt_small_corner.gltf",
			"floor_dirt_small_weeds.gltf",
			"floor_dirt_large.gltf",
			"floor_dirt_large_rocky.gltf",
			"floor_foundation_front.gltf",
			"floor_foundation_front_and_back.gltf",
			"floor_foundation_front_and_sides.gltf",
			"floor_foundation_corner.gltf",
			"floor_foundation_diagonal_corner.gltf",
			"floor_foundation_allsides.gltf",
		],
		type: "floor",
	},
	
	// Dungeon Pack - Walls and other objects
	dungeon: {
		catName: "Donjon",
		basePath: "/packages/KayKit_DungeonRemastered_1.1_FREE/Assets/gltf",
		files: [
			"wall.gltf", "wall_corner.gltf", "wall_corner_small.gltf", "wall_corner_gated.gltf",
			"wall_corner_scaffold.gltf", "wall_cracked.gltf", "wall_broken.gltf",
			"wall_doorway.gltf", "wall_doorway_sides.gltf", "wall_doorway_scaffold.gltf",
			"wall_doorway_Tsplit.gltf", "wall_window_closed.gltf", "wall_window_open.gltf",
			"wall_window_closed_scaffold.gltf", "wall_window_open_scaffold.gltf",
			"wall_arched.gltf", "wall_archedwindow_gated.gltf", "wall_archedwindow_open.gltf",
			"wall_gated.gltf", "wall_half.gltf", "wall_half_endcap.gltf",
			"wall_open_scaffold.gltf", "wall_pillar.gltf", "wall_scaffold.gltf",
			"wall_shelves.gltf", "wall_sloped.gltf", "wall_Tsplit.gltf",
			"wall_Tsplit_sloped.gltf", "wall_endcap.gltf", "wall_crossing.gltf",
			"torch.gltf", "torch_lit.gltf", "torch_mounted.gltf",
			"table_small.gltf", "table_small_decorated_A.gltf", "table_small_decorated_B.gltf",
			"trunk_small_A.gltf", "trunk_small_B.gltf", "trunk_small_C.gltf",
			"trunk_medium_A.gltf", "trunk_medium_B.gltf", "trunk_medium_C.gltf",
			"trunk_large_A.gltf", "trunk_large_B.gltf", "trunk_large_C.gltf",
		],
		type: "wall",
	},

	// Block Bits Pack
	blockBits: {
		catName: "Blocks",
		basePath: "/packages/KayKit_BlockBits_1.0_FREE/Assets/gltf",
		files: [
			"bricks_A.gltf", "bricks_B.gltf",
			"colored_block_blue.gltf", "colored_block_green.gltf", "colored_block_red.gltf", "colored_block_yellow.gltf",
			"decorative_block_blue.gltf", "decorative_block_green.gltf", "decorative_block_red.gltf", "decorative_block_yellow.gltf",
			"striped_block_blue.gltf", "striped_block_green.gltf", "striped_block_red.gltf", "striped_block_yellow.gltf",
			"dirt.gltf", "dirt_with_grass.gltf", "dirt_with_snow.gltf",
			"grass.gltf", "grass_with_snow.gltf",
			"gravel.gltf", "gravel_with_grass.gltf", "gravel_with_snow.gltf",
			"sand_A.gltf", "sand_B.gltf", "sand_with_grass.gltf", "sand_with_snow.gltf",
			"snow.gltf", "stone.gltf", "stone_dark.gltf",
			"stone_with_copper.gltf", "stone_with_gold.gltf", "stone_with_silver.gltf",
			"wood.gltf", "water.gltf", "lava.gltf", "glass.gltf", "metal.gltf",
			"prototype.gltf", "tree.gltf", "tree_with_snow.gltf",
		],
		type: "block",
	},

	// Furniture Pack
	furniture: {
		catName: "Décorations",
		basePath: "/packages/KayKit_Furniture_Bits_1.0_FREE/Assets/gltf",
		files: [
			"bed_single_A.gltf", "bed_single_B.gltf",
			"chair_A.gltf", "chair_A_wood.gltf", "chair_B.gltf", "chair_B_wood.gltf", "chair_C.gltf",
			"chair_stool.gltf", "chair_stool_wood.gltf",
			"couch.gltf", "couch_pillows.gltf",
			"table_small.gltf", "table_medium.gltf", "table_medium_long.gltf", "table_low.gltf",
			"cabinet_small.gltf", "cabinet_small_decorated.gltf", "cabinet_medium.gltf", "cabinet_medium_decorated.gltf",
			"shelf_A_small.gltf", "shelf_A_big.gltf",
			"shelf_B_small.gltf", "shelf_B_small_decorated.gltf", "shelf_B_large.gltf", "shelf_B_large_decorated.gltf",
			"lamp_table.gltf", "lamp_standing.gltf",
			"rug_oval_A.gltf", "rug_oval_B.gltf", "rug_rectangle_A.gltf", "rug_rectangle_B.gltf",
			"rug_rectangle_stripes_A.gltf", "rug_rectangle_stripes_B.gltf",
			"pillow_A.gltf", "pillow_B.gltf",
			"pictureframe_small_A.gltf", "pictureframe_small_B.gltf", "pictureframe_small_C.gltf",
			"pictureframe_medium.gltf", "pictureframe_large_A.gltf", "pictureframe_large_B.gltf",
			"pictureframe_standing_A.gltf", "pictureframe_standing_B.gltf",
			"book_single.gltf", "book_set.gltf",
			"cactus_small_A.gltf", "cactus_small_B.gltf", "cactus_medium_A.gltf", "cactus_medium_B.gltf",
		],
		type: "furniture",
	},

	// Resource Bits Pack
	resources: {
		catName: "Décorations",
		basePath: "/packages/KayKit_ResourceBits_1.0_FREE/Assets/gltf",
		files: [
			"Wood_Log_A.gltf", "Wood_Log_B.gltf", "Wood_Log_Stack.gltf",
			"Wood_Plank_A.gltf", "Wood_Plank_B.gltf", "Wood_Plank_C.gltf",
			"Wood_Planks_Stack_Small.gltf", "Wood_Planks_Stack_Medium.gltf", "Wood_Planks_Stack_Large.gltf",
			"Stone_Brick.gltf", "Stone_Bricks_Stack_Small.gltf", "Stone_Bricks_Stack_Medium.gltf", "Stone_Bricks_Stack_Large.gltf",
			"Stone_Chunks_Small.gltf", "Stone_Chunks_Large.gltf",
			"Iron_Bar.gltf", "Iron_Bars.gltf",
			"Iron_Bars_Stack_Small.gltf", "Iron_Bars_Stack_Medium.gltf", "Iron_Bars_Stack_Large.gltf",
			"Iron_Nugget_Small.gltf", "Iron_Nugget_Medium.gltf", "Iron_Nugget_Large.gltf", "Iron_Nuggets.gltf",
			"Gold_Bar.gltf", "Gold_Bars.gltf",
			"Gold_Bars_Stack_Small.gltf", "Gold_Bars_Stack_Medium.gltf", "Gold_Bars_Stack_Large.gltf",
			"Gold_Nugget_Small.gltf", "Gold_Nugget_Medium.gltf", "Gold_Nugget_Large.gltf", "Gold_Nuggets.gltf",
			"Silver_Bar.gltf", "Silver_Bars.gltf",
			"Silver_Bars_Stack_Small.gltf", "Silver_Bars_Stack_Medium.gltf", "Silver_Bars_Stack_Large.gltf",
			"Silver_Nugget_Small.gltf", "Silver_Nugget_Medium.gltf", "Silver_Nugget_Large.gltf", "Silver_Nuggets.gltf",
			"Textiles_A.gltf", "Textiles_B.gltf", "Textiles_C.gltf",
			"Textiles_Stack_Large.gltf", "Textiles_Stack_Large_Colored.gltf", "Textiles_Stack_Small.gltf",
			"Pallet_Wood.gltf", "Pallet_Wood_Covered_A.gltf", "Pallet_Wood_Covered_B.gltf",
			"Parts_Cog.gltf", "Parts_Pile_Small.gltf", "Parts_Pile_Medium.gltf", "Parts_Pile_Large.gltf",
		],
		type: "resource",
	},

	// RPG Tools Pack
	rpgTools: {
		catName: "Outils et équipements",
		basePath: "/packages/KayKit_RPGToolsBits_1.0_FREE/Assets/gltf",
		files: [
			"anvil.gltf", "axe.gltf", "blueprint.gltf", "blueprint_stacked.gltf",
			"bucket_metal.gltf", "chisel.gltf", "compass_base.gltf", "drafting_compass.gltf",
			"file.gltf", "grindstone.gltf", "hammer.gltf", "handdrill.gltf", "handplane.gltf",
			"journal_closed.gltf", "journal_open.gltf", "knife.gltf", "lantern.gltf",
			"magnifying_glass.gltf", "mallet.gltf", "map.gltf", "map_empty.gltf", "map_rolled.gltf",
			"nail.gltf", "pencil_A_long.gltf", "pencil_A_short.gltf", "pencil_B_long.gltf", "pencil_B_short.gltf",
			"pickaxe.gltf", "rope_bundle_A.gltf", "rope_bundle_B.gltf",
			"saw.gltf", "scissors.gltf", "screw_A.gltf", "screw_B.gltf",
			"screwdriver_A_long.gltf", "screwdriver_A_long_color.gltf", "screwdriver_A_short.gltf", "screwdriver_A_short_color.gltf",
			"screwdriver_B_long.gltf", "screwdriver_B_long_color.gltf", "screwdriver_B_short.gltf", "screwdriver_B_short_color.gltf",
			"shovel.gltf", "tongs.gltf", "torch.gltf", "torch_burnt.gltf",
			"trowel.gltf", "wrench_A.gltf", "wrench_B.gltf",
		],
		type: "decoration",
	},

	// Halloween Pack
	halloween: {
		catName: "Halloween",
		basePath: "/packages/KayKit_HalloweenBits_1.0_FREE/Assets/gltf",
		files: [
			"arch.gltf", "arch_gate.gltf", "bench.gltf", "bench_decorated.gltf",
			"bone_A.gltf", "bone_B.gltf", "bone_C.gltf",
			"candle.gltf", "candle_melted.gltf", "candle_thin.gltf", "candle_triple.gltf",
			"coffin.gltf", "coffin_decorated.gltf", "crypt.gltf",
			"fence.gltf", "fence_broken.gltf", "fence_gate.gltf", "fence_pillar.gltf",
			"fence_pillar_broken.gltf", "fence_seperate.gltf", "fence_seperate_broken.gltf",
			"floor_dirt.gltf", "floor_dirt_grave.gltf", "floor_dirt_small.gltf",
			"grave_A.gltf", "grave_A_destroyed.gltf", "grave_B.gltf",
			"gravemarker_A.gltf", "gravemarker_B.gltf", "gravestone.gltf",
			"lantern_hanging.gltf", "lantern_standing.gltf",
			"path_A.gltf", "path_B.gltf", "path_C.gltf", "path_D.gltf",
			"pillar.gltf", "plaque.gltf", "plaque_candles.gltf",
			"post.gltf", "post_lantern.gltf", "post_skull.gltf",
			"pumpkin_orange.gltf", "pumpkin_orange_jackolantern.gltf", "pumpkin_orange_small.gltf",
			"pumpkin_yellow.gltf", "pumpkin_yellow_jackolantern.gltf", "pumpkin_yellow_small.gltf",
			"ribcage.gltf", "shrine.gltf", "shrine_candles.gltf",
			"skull.gltf", "skull_candle.gltf",
			"tree_dead_large.gltf", "tree_dead_large_decorated.gltf", "tree_dead_medium.gltf", "tree_dead_small.gltf",
			"tree_pine_orange_large.gltf", "tree_pine_orange_medium.gltf", "tree_pine_orange_small.gltf",
			"tree_pine_yellow_large.gltf", "tree_pine_yellow_medium.gltf", "tree_pine_yellow_small.gltf",
		],
		type: "decoration",
	},

	// Prototype Bits Pack
	prototype: {
		catName: "Textures",
		basePath: "/packages/KayKit_Prototype_Bits_1.1_FREE/Assets/gltf",
		files: [
			"Barrel_A.gltf", "Barrel_B.gltf", "Barrel_C.gltf",
			"Box_A.gltf", "Box_B.gltf", "Box_C.gltf",
			"Can_A.gltf", "Can_B.gltf",
			"Coin_A.gltf", "Coin_B.gltf", "Coin_C.gltf",
			"Cube_Prototype_Large_A.gltf", "Cube_Prototype_Large_B.gltf", "Cube_Prototype_Small.gltf",
			"Door_A.gltf", "Door_A_Decorated.gltf", "Door_B.gltf",
			"Dummy_Base.gltf",
			"Floor.gltf", "Floor_Dirt.gltf", "Floor_Prototype.gltf",
			"Pallet_Large.gltf", "Pallet_Small.gltf", "Pallet_Small_Decorated_A.gltf", "Pallet_Small_Decorated_B.gltf",
			"Pillar_A.gltf", "Pillar_B.gltf",
			"Primitive_Beam.gltf", "Primitive_Cube.gltf", "Primitive_Cube_Small.gltf",
			"Primitive_Doorway.gltf", "Primitive_Floor.gltf", "Primitive_Floor_Hole.gltf", "Primitive_Pillar.gltf",
			"Primitive_Slope.gltf", "Primitive_Slope_Half.gltf",
			"Primitive_Slope_Half_InnerCorner.gltf", "Primitive_Slope_Half_OuterCorner.gltf",
			"Primitive_Slope_InnerCorner.gltf", "Primitive_Slope_OuterCorner.gltf",
			"Primitive_Stairs.gltf", "Primitive_Stairs_Half.gltf",
			"Primitive_Wall.gltf", "Primitive_Wall_Half.gltf", "Primitive_Wall_OpenCorner.gltf",
			"Primitive_Wall_Short.gltf", "Primitive_Wall_Slope.gltf", "Primitive_Window.gltf",
			"table_medium.gltf", "table_medium_Decorated.gltf", "table_medium_long.gltf",
			"target.gltf", "target_pieces_A.gltf", "target_pieces_B.gltf", "target_pieces_C.gltf",
			"target_pieces_D.gltf", "target_pieces_E.gltf", "target_pieces_F.gltf",
			"target_small.gltf", "target_stand_A.gltf", "target_stand_A_Decorated.gltf", "target_stand_B.gltf",
			"target_wall_large_A.gltf", "target_wall_large_B.gltf", "target_wall_small.gltf",
			"Wall.gltf", "Wall_Decorated.gltf", "Wall_Doorway.gltf", "Wall_Half.gltf",
			"Wall_Target.gltf", "Wall_Window_Closed.gltf", "Wall_Window_Open.gltf",
		],
		type: "decoration",
	},

	// Adventurers Pack
	adventurers: {
		catName: "Outils et équipements",
		basePath: "/packages/KayKit_Adventurers_2.0_FREE/Assets/gltf",
		files: [
			"arrow_bow.gltf", "arrow_bow_bundle.gltf", "arrow_crossbow.gltf", "arrow_crossbow_bundle.gltf",
			"axe_1handed.gltf", "axe_2handed.gltf",
			"bow.gltf", "bow_withString.gltf",
			"crossbow_1handed.gltf", "crossbow_2handed.gltf",
			"dagger.gltf", "mug_empty.gltf", "mug_full.gltf", "quiver.gltf",
			"shield_badge.gltf", "shield_badge_color.gltf",
			"shield_round.gltf", "shield_round_barbarian.gltf", "shield_round_color.gltf",
			"shield_spikes.gltf", "shield_spikes_color.gltf",
			"shield_square.gltf", "shield_square_color.gltf",
			"smokebomb.gltf",
			"spellbook_closed.gltf", "spellbook_open.gltf",
			"staff.gltf",
			"sword_1handed.gltf", "sword_2handed.gltf", "sword_2handed_color.gltf",
			"wand.gltf",
		],
		type: "decoration",
	},

	// Skeletons Pack - Assets only (weapons/equipment, not characters)
	skeletons: {
		catName: "Outils et équipements",
		basePath: "/packages/KayKit_Skeletons_1.1_FREE/assets/gltf",
		files: [
			"Skeleton_Arrow.gltf", "Skeleton_Arrow_Broken.gltf", "Skeleton_Arrow_Broken_Half.gltf", "Skeleton_Arrow_Half.gltf",
			"Skeleton_Axe.gltf", "Skeleton_Blade.gltf", "Skeleton_Crossbow.gltf",
			"Skeleton_Quiver.gltf", "Skeleton_Staff.gltf",
			"Skeleton_Shield_Large_A.gltf", "Skeleton_Shield_Large_B.gltf",
			"Skeleton_Shield_Small_A.gltf", "Skeleton_Shield_Small_B.gltf",
		],
		type: "decoration",
	},

	// Platformer Pack - Files are in subdirectories (blue, green, yellow)
	platformer: {
		catName: "Platformer",
		basePath: "/packages/KayKit_Platformer_Pack_1.0_FREE/Assets/gltf",
		files: [
			// Blue variants
			"blue/arch_blue.gltf", "blue/arch_tall_blue.gltf", "blue/arch_wide_blue.gltf",
			"blue/ball_blue.gltf", "blue/cone_blue.gltf", "blue/diamond_blue.gltf",
			"blue/heart_blue.gltf", "blue/star_blue.gltf",
			"blue/barrier_1x1x1_blue.gltf", "blue/barrier_1x1x2_blue.gltf", "blue/barrier_1x1x4_blue.gltf",
			"blue/barrier_2x1x1_blue.gltf", "blue/barrier_2x1x2_blue.gltf", "blue/barrier_2x1x4_blue.gltf",
			"blue/barrier_3x1x1_blue.gltf", "blue/barrier_3x1x2_blue.gltf", "blue/barrier_3x1x4_blue.gltf",
			"blue/barrier_4x1x1_blue.gltf", "blue/barrier_4x1x2_blue.gltf", "blue/barrier_4x1x4_blue.gltf",
			"blue/platform_1x1x1_blue.gltf", "blue/platform_2x2x1_blue.gltf", "blue/platform_2x2x2_blue.gltf",
			"blue/platform_2x2x4_blue.gltf", "blue/platform_4x2x1_blue.gltf", "blue/platform_4x2x2_blue.gltf",
			"blue/platform_4x2x4_blue.gltf", "blue/platform_4x4x1_blue.gltf", "blue/platform_4x4x2_blue.gltf",
			"blue/platform_4x4x4_blue.gltf", "blue/platform_6x2x1_blue.gltf", "blue/platform_6x2x2_blue.gltf",
			"blue/platform_6x2x4_blue.gltf", "blue/platform_6x6x1_blue.gltf", "blue/platform_6x6x2_blue.gltf",
			"blue/platform_6x6x4_blue.gltf", "blue/platform_arrow_2x2x1_blue.gltf", "blue/platform_arrow_4x4x1_blue.gltf",
			"blue/platform_decorative_1x1x1_blue.gltf", "blue/platform_decorative_2x2x2_blue.gltf",
			"blue/platform_hole_6x6x1_blue.gltf", "blue/platform_slope_2x2x2_blue.gltf", "blue/platform_slope_2x4x4_blue.gltf",
			"blue/platform_slope_2x6x4_blue.gltf", "blue/platform_slope_4x2x2_blue.gltf", "blue/platform_slope_4x4x4_blue.gltf",
			"blue/platform_slope_4x6x4_blue.gltf", "blue/platform_slope_6x2x2_blue.gltf", "blue/platform_slope_6x4x4_blue.gltf",
			"blue/platform_slope_6x6x4_blue.gltf", "blue/pipe_180_A_blue.gltf", "blue/pipe_180_B_blue.gltf",
			"blue/pipe_90_A_blue.gltf", "blue/pipe_90_B_blue.gltf", "blue/pipe_end_blue.gltf",
			"blue/pipe_straight_A_blue.gltf", "blue/pipe_straight_B_blue.gltf",
			"blue/railing_corner_double_blue.gltf", "blue/railing_corner_padded_blue.gltf", "blue/railing_corner_single_blue.gltf",
			"blue/railing_straight_double_blue.gltf", "blue/railing_straight_padded_blue.gltf", "blue/railing_straight_single_blue.gltf",
			"blue/bomb_A_blue.gltf", "blue/bomb_B_blue.gltf", "blue/bracing_large_blue.gltf",
			"blue/bracing_medium_blue.gltf", "blue/bracing_small_blue.gltf", "blue/button_base_blue.gltf",
			"blue/flag_A_blue.gltf", "blue/flag_B_blue.gltf", "blue/flag_C_blue.gltf",
			"blue/hoop_angled_blue.gltf", "blue/hoop_blue.gltf", "blue/lever_floor_base_blue.gltf",
			"blue/lever_wall_base_A_blue.gltf", "blue/lever_wall_base_B_blue.gltf", "blue/power_blue.gltf",
			"blue/signage_arrow_stand_blue.gltf", "blue/signage_arrow_wall_blue.gltf",
			"blue/signage_arrows_left_blue.gltf", "blue/signage_arrows_right_blue.gltf",
			"blue/spring_pad_blue.gltf",
			// Green variants
			"green/arch_green.gltf", "green/arch_tall_green.gltf", "green/arch_wide_green.gltf",
			"green/ball_green.gltf", "green/cone_green.gltf", "green/diamond_green.gltf",
			"green/heart_green.gltf", "green/star_green.gltf",
			"green/barrier_1x1x1_green.gltf", "green/barrier_1x1x2_green.gltf", "green/barrier_1x1x4_green.gltf",
			"green/barrier_2x1x1_green.gltf", "green/barrier_2x1x2_green.gltf", "green/barrier_2x1x4_green.gltf",
			"green/barrier_3x1x1_green.gltf", "green/barrier_3x1x2_green.gltf", "green/barrier_3x1x4_green.gltf",
			"green/barrier_4x1x1_green.gltf", "green/barrier_4x1x2_green.gltf", "green/barrier_4x1x4_green.gltf",
			"green/platform_1x1x1_green.gltf", "green/platform_2x2x1_green.gltf", "green/platform_2x2x2_green.gltf",
			"green/platform_2x2x4_green.gltf", "green/platform_4x2x1_green.gltf", "green/platform_4x2x2_green.gltf",
			"green/platform_4x2x4_green.gltf", "green/platform_4x4x1_green.gltf", "green/platform_4x4x2_green.gltf",
			"green/platform_4x4x4_green.gltf", "green/platform_6x2x1_green.gltf", "green/platform_6x2x2_green.gltf",
			"green/platform_6x2x4_green.gltf", "green/platform_6x6x1_green.gltf", "green/platform_6x6x2_green.gltf",
			"green/platform_6x6x4_green.gltf", "green/platform_arrow_2x2x1_green.gltf", "green/platform_arrow_4x4x1_green.gltf",
			"green/platform_decorative_1x1x1_green.gltf", "green/platform_decorative_2x2x2_green.gltf",
			"green/platform_hole_6x6x1_green.gltf", "green/platform_slope_2x2x2_green.gltf", "green/platform_slope_2x4x4_green.gltf",
			"green/platform_slope_2x6x4_green.gltf", "green/platform_slope_4x2x2_green.gltf", "green/platform_slope_4x4x4_green.gltf",
			"green/platform_slope_4x6x4_green.gltf", "green/platform_slope_6x2x2_green.gltf", "green/platform_slope_6x4x4_green.gltf",
			"green/platform_slope_6x6x4_green.gltf", "green/pipe_180_A_green.gltf", "green/pipe_180_B_green.gltf",
			"green/pipe_90_A_green.gltf", "green/pipe_90_B_green.gltf", "green/pipe_end_green.gltf",
			"green/pipe_straight_A_green.gltf", "green/pipe_straight_B_green.gltf",
			"green/railing_corner_double_green.gltf", "green/railing_corner_padded_green.gltf", "green/railing_corner_single_green.gltf",
			"green/railing_straight_double_green.gltf", "green/railing_straight_padded_green.gltf", "green/railing_straight_single_green.gltf",
			"green/bomb_A_green.gltf", "green/bomb_B_green.gltf", "green/bracing_large_green.gltf",
			"green/bracing_medium_green.gltf", "green/bracing_small_green.gltf", "green/button_base_green.gltf",
			"green/flag_A_green.gltf", "green/flag_B_green.gltf", "green/flag_C_green.gltf",
			"green/hoop_angled_green.gltf", "green/hoop_green.gltf", "green/lever_floor_base_green.gltf",
			"green/lever_wall_base_A_green.gltf", "green/lever_wall_base_B_green.gltf", "green/power_green.gltf",
			"green/signage_arrow_stand_green.gltf", "green/signage_arrow_wall_green.gltf",
			"green/signage_arrows_left_green.gltf", "green/signage_arrows_right_green.gltf",
			"green/spring_pad_green.gltf",
			// Base files (no color suffix)
			"ball.gltf", "cone.gltf", "bomb.gltf", "sign.gltf", "spring.gltf",
			"barrier_1x1x1.gltf", "barrier_1x1x2.gltf", "barrier_1x1x4.gltf",
			"barrier_2x1x1.gltf", "barrier_2x1x2.gltf", "barrier_2x1x4.gltf",
			"barrier_3x1x1.gltf", "barrier_3x1x2.gltf", "barrier_3x1x4.gltf",
			"barrier_4x1x1.gltf", "barrier_4x1x2.gltf", "barrier_4x1x4.gltf",
			"floor_wood_1x1.gltf", "floor_wood_2x2.gltf", "floor_wood_2x6.gltf", "floor_wood_4x4.gltf",
			"pillar_1x1x1.gltf", "pillar_1x1x2.gltf", "pillar_1x1x4.gltf", "pillar_1x1x8.gltf",
			"pillar_2x2x2.gltf", "pillar_2x2x4.gltf", "pillar_2x2x8.gltf",
			"platform_wood_1x1x1.gltf", "signage_arrows_left.gltf", "signage_arrows_right.gltf",
			"signage_finish.gltf", "signage_finish_wide.gltf", "structure_A.gltf",
			// Basic shapes
			"arch.gltf", "arch_blue.gltf", "arch_green.gltf",
			"arch_tall_blue.gltf", "arch_tall_green.gltf",
			"arch_wide_blue.gltf", "arch_wide_green.gltf",
			"ball.gltf", "ball_blue.gltf", "ball_green.gltf",
			"cone.gltf", "cone_blue.gltf", "cone_green.gltf",
			"diamond_blue.gltf", "diamond_green.gltf",
			"heart_blue.gltf", "heart_green.gltf",
			"star_blue.gltf", "star_green.gltf",
			// Barriers
			"barrier_1x1x1.gltf", "barrier_1x1x1_blue.gltf", "barrier_1x1x1_green.gltf",
			"barrier_1x1x2.gltf", "barrier_1x1x2_blue.gltf", "barrier_1x1x2_green.gltf",
			"barrier_1x1x4.gltf", "barrier_1x1x4_blue.gltf", "barrier_1x1x4_green.gltf",
			"barrier_2x1x1.gltf", "barrier_2x1x1_blue.gltf", "barrier_2x1x1_green.gltf",
			"barrier_2x1x2.gltf", "barrier_2x1x2_blue.gltf", "barrier_2x1x2_green.gltf",
			"barrier_2x1x4.gltf", "barrier_2x1x4_blue.gltf", "barrier_2x1x4_green.gltf",
			"barrier_3x1x1.gltf", "barrier_3x1x1_blue.gltf", "barrier_3x1x1_green.gltf",
			"barrier_3x1x2.gltf", "barrier_3x1x2_blue.gltf", "barrier_3x1x2_green.gltf",
			"barrier_3x1x4.gltf", "barrier_3x1x4_blue.gltf", "barrier_3x1x4_green.gltf",
			"barrier_4x1x1.gltf", "barrier_4x1x1_blue.gltf", "barrier_4x1x1_green.gltf",
			"barrier_4x1x2.gltf", "barrier_4x1x2_blue.gltf", "barrier_4x1x2_green.gltf",
			"barrier_4x1x4.gltf", "barrier_4x1x4_blue.gltf", "barrier_4x1x4_green.gltf",
			// Platforms
			"platform_1x1x1_blue.gltf", "platform_1x1x1_green.gltf",
			"platform_2x2x1_blue.gltf", "platform_2x2x1_green.gltf",
			"platform_2x2x2_blue.gltf", "platform_2x2x2_green.gltf",
			"platform_2x2x4_blue.gltf", "platform_2x2x4_green.gltf",
			"platform_4x2x1_blue.gltf", "platform_4x2x1_green.gltf",
			"platform_4x2x2_blue.gltf", "platform_4x2x2_green.gltf",
			"platform_4x2x4_blue.gltf", "platform_4x2x4_green.gltf",
			"platform_4x4x1_blue.gltf", "platform_4x4x1_green.gltf",
			"platform_4x4x2_blue.gltf", "platform_4x4x2_green.gltf",
			"platform_4x4x4_blue.gltf", "platform_4x4x4_green.gltf",
			"platform_6x2x1_blue.gltf", "platform_6x2x1_green.gltf",
			"platform_6x2x2_blue.gltf", "platform_6x2x2_green.gltf",
			"platform_6x2x4_blue.gltf", "platform_6x2x4_green.gltf",
			"platform_6x6x1_blue.gltf", "platform_6x6x1_green.gltf",
			"platform_6x6x2_blue.gltf", "platform_6x6x2_green.gltf",
			"platform_6x6x4_blue.gltf", "platform_6x6x4_green.gltf",
			"platform_arrow_2x2x1_blue.gltf", "platform_arrow_2x2x1_green.gltf",
			"platform_arrow_4x4x1_blue.gltf", "platform_arrow_4x4x1_green.gltf",
			"platform_decorative_1x1x1_blue.gltf", "platform_decorative_1x1x1_green.gltf",
			"platform_decorative_2x2x2_blue.gltf", "platform_decorative_2x2x2_green.gltf",
			"platform_hole_6x6x1_blue.gltf", "platform_hole_6x6x1_green.gltf",
			"platform_slope_2x2x2_blue.gltf", "platform_slope_2x2x2_green.gltf",
			"platform_slope_2x4x4_blue.gltf", "platform_slope_2x4x4_green.gltf",
			"platform_slope_2x6x4_blue.gltf", "platform_slope_2x6x4_green.gltf",
			"platform_slope_4x2x2_blue.gltf", "platform_slope_4x2x2_green.gltf",
			"platform_slope_4x4x4_blue.gltf", "platform_slope_4x4x4_green.gltf",
			"platform_slope_4x6x4_blue.gltf", "platform_slope_4x6x4_green.gltf",
			"platform_slope_6x2x2_blue.gltf", "platform_slope_6x2x2_green.gltf",
			"platform_slope_6x4x4_blue.gltf", "platform_slope_6x4x4_green.gltf",
			"platform_slope_6x6x4_blue.gltf", "platform_slope_6x6x4_green.gltf",
			"platform_wood_1x1x1.gltf",
			// Pillars
			"pillar_1x1x1.gltf", "pillar_1x1x2.gltf", "pillar_1x1x4.gltf", "pillar_1x1x8.gltf",
			"pillar_2x2x2.gltf", "pillar_2x2x4.gltf", "pillar_2x2x8.gltf",
			// Pipes
			"pipe_180_A_blue.gltf", "pipe_180_A_green.gltf",
			"pipe_180_B_blue.gltf", "pipe_180_B_green.gltf",
			"pipe_90_A_blue.gltf", "pipe_90_A_green.gltf",
			"pipe_90_B_blue.gltf", "pipe_90_B_green.gltf",
			"pipe_end_blue.gltf", "pipe_end_green.gltf",
			"pipe_straight_A_blue.gltf", "pipe_straight_A_green.gltf",
			"pipe_straight_B_blue.gltf", "pipe_straight_B_green.gltf",
			// Railings
			"railing_corner_double_blue.gltf", "railing_corner_double_green.gltf",
			"railing_corner_padded_blue.gltf", "railing_corner_padded_green.gltf",
			"railing_corner_single_blue.gltf", "railing_corner_single_green.gltf",
			"railing_straight_double_blue.gltf", "railing_straight_double_green.gltf",
			"railing_straight_padded_blue.gltf", "railing_straight_padded_green.gltf",
			"railing_straight_single_blue.gltf", "railing_straight_single_green.gltf",
			// Other elements
			"bomb.gltf", "bomb_A_blue.gltf", "bomb_A_green.gltf", "bomb_B_blue.gltf", "bomb_B_green.gltf",
			"bracing_large_blue.gltf", "bracing_large_green.gltf",
			"bracing_medium_blue.gltf", "bracing_medium_green.gltf",
			"bracing_small_blue.gltf", "bracing_small_green.gltf",
			"button_base_blue.gltf", "button_base_green.gltf",
			"flag_A_blue.gltf", "flag_A_green.gltf",
			"flag_B_blue.gltf", "flag_B_green.gltf",
			"flag_C_blue.gltf", "flag_C_green.gltf",
			"floor_wood_1x1.gltf", "floor_wood_2x2.gltf", "floor_wood_2x6.gltf", "floor_wood_4x4.gltf",
			"hoop_angled_blue.gltf", "hoop_angled_green.gltf",
			"hoop_blue.gltf", "hoop_green.gltf",
			"lever_floor_base_blue.gltf", "lever_floor_base_green.gltf",
			"lever_wall_base_A_blue.gltf", "lever_wall_base_A_green.gltf",
			"lever_wall_base_B_blue.gltf", "lever_wall_base_B_green.gltf",
			"power_blue.gltf", "power_green.gltf",
			"sign.gltf",
			"signage_arrow_stand_blue.gltf", "signage_arrow_stand_green.gltf",
			"signage_arrow_wall_blue.gltf", "signage_arrow_wall_green.gltf",
			"signage_arrows_left.gltf", "signage_arrows_left_blue.gltf", "signage_arrows_left_green.gltf",
			"signage_arrows_right.gltf", "signage_arrows_right_blue.gltf", "signage_arrows_right_green.gltf",
			"signage_finish.gltf", "signage_finish_wide.gltf",
			"spring.gltf", "spring_pad_blue.gltf", "spring_pad_green.gltf",
			"structure_A.gltf",
		],
		type: "decoration",
	},
};
